version: '3.8'

services:
  # The Django Backend Service
  backend:
    build:
      context: ./agentic_project
    ports:
      - "8000:8000"
    # Pass the API key as an environment variable from our local .env file
    env_file:
      - ./agentic_project/.env
    # Name the container so the frontend can find it
    container_name: agentic_backend

  # The React Frontend Service (served by Nginx)
  frontend:
    build:
      context: ./agentic-ui
    ports:
      - "3000:80" # Map host port 3000 to container port 80
    # This service depends on the backend starting first
    depends_on:
      - backend