from django.shortcuts import render

# Create your views here.
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .agents import create_outreach_crew  # Import our AI crew function

class GenerateOutreachView(APIView):
    """
    This view handles POST requests to generate personalized outreach emails.
    It expects 'company_url' and 'product_description' in the request body.
    """
    def post(self, request, *args, **kwargs):
        # 1. Get the data from the incoming request
        company_url = request.data.get('company_url')
        product_description = request.data.get('product_description')

        # 2. Validate the input
        if not company_url or not product_description:
            return Response(
                {"error": "Both company_url and product_description are required."},
                status=status.HTTP_400_BAD_REQUEST
            )

        try:
            # 3. This is where we run your AI crew!
            # The result will be the final email generated by the copywriter agent.
            print("Kicking off the AI crew...")
            result = create_outreach_crew(company_url, product_description)
            print("AI crew finished.")

            final_email = result.raw if hasattr(result, 'raw') else result
            
            # 4. Return the successful response
            return Response({"email": final_email}, status=status.HTTP_200_OK)

        except Exception as e:
            # 5. Handle any potential errors gracefully
            print(f"An error occurred: {e}")
            return Response(
                {"error": f"An unexpected error occurred while processing your request. Details: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )